run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - bodyclose
    - noctx
    - gosec
    - prealloc
    - misspell
    - unconvert
    - unparam
    - errorlint

linters-settings:
  govet:
    shadow: true
  gosec:
    excludes:
      - G104  # unhandled errors on deferred Close — acceptable
  errcheck:
    check-type-assertions: true

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 50
  max-same-issues: 5
